import React, { useState, useEffect } from 'react';
import Layout from '../../components/Layout';
import Head from 'next/head';
import UserCard from '../../components/reservations/UserCard';
import BookingModal from '../../components/Modal/index';
import Search from '../../components/SVGs/Search';
import Link from 'next/link';
import getHeader from '../../utilis/getHeader';
import API from '../../utilis/API';
import Loader from '../../components/Loader';
import PaginationElement from '../../components/PaginationElement';

const index = () => {


    const [cardsData, setCardsData] = useState([

    ]);
    const [loading, setloading] = useState(false);
    const [villasList, setVillasList] = useState([]);

    // For pagination
    const [pageNumber, setPageNumber] = useState(1)
    const [lastPage, setLastPage] = useState();


    const loadVillasList = async () => {
        setloading(true)
        try {
            const header = getHeader()
            const { data } = await API.get(`Dashboard/all/villaapprovals?page=${pageNumber}`, header)
            console.log("approvals:", data);

            setCardsData([
                {
                    title: 'All Villas',
                    value: data?.body?.approved,
                    color: '#2E3039'
                },
                {
                    title: 'Pending',
                    value: data?.body?.pending,
                    color: '#F52D56'
                },
                {
                    title: 'New Approvals',
                    value: data?.body?.new_request,
                    color: '#08488C'
                }
            ])
            setVillasList(data?.body?.all?.data)
            setLastPage(data?.body?.all?.last_page);

            setloading(false)
        } catch (error) {
            console.log(error)
            setloading(false)
        }
    }


    useEffect(() => {
        loadVillasList()
    }, [pageNumber]);

    return (
        <>
            <Head>
                <title>Villas Approvals</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout title="Villa Approvals" slug="Check the Vendors villa">
                {/* Cards  Start*/}
                <section className='w-full border-b pb-8'>
                    <div className='flex flex-row flex-wrap space-x-[24px] gap-y-5 mt-[29px]'>
                        {
                            cardsData?.map((item, index) => {
                                return (
                                    <div
                                        key={index + ''}
                                        className='w-[209px] h-[135px] bg-white rounded-[8px] flex flex-col pt-[22px] px-[25px]'
                                        style={{
                                            'boxShadow': '0px 0px 20px #D7DEE365'
                                        }}
                                    >
                                        <h1 className={`font-roboto text-darkBlack text-xl font-medium`}>{item?.title}</h1>
                                        <h2 className={`font-roboto font-bold text-[${item?.color}] text-2xl mt-[13px]`}>{item?.value}</h2>
                                    </div>
                                )
                            })
                        }
                    </div>
                </section>
                <section className='mt-8'>
                    <div className='flex flex-wrap justify-between gap-y-8'>
                        <div className='flex gap-x-12 items-center'>
                            <h3 className='text-2xl font-sans font-medium text-black'>New Villa Request</h3>
                            <div className='w-[192px] h-[35px] relative'>
                                <select
                                    className='w-full h-full text-sm text-darkBlack appearance-none rounded-[25px] border border-[#EAEDEF] px-5'
                                    style={{ boxShadow: '0px 2px 20px #CFD9DF66' }}
                                >
                                    <option selected>Today</option>
                                </select>
                                <img src='/img/down.svg' alt="down" className='absolute right-4 top-1/2 -translate-y-1/2 w-[20px] h-[12px]' />
                            </div>
                        </div>
                        <div className='flex gap-x-12'>
                            <Link href="/villas/pending_villas">
                                <button className='font-medium text-danger text-xs'>Pending List</button>
                            </Link>
                            <Link href="/villas/villas_list">
                                <button className='w-[150px] h-[42px] text-white text-xs rounded-xl bg-primary'>All Villas</button>
                            </Link>
                        </div>
                    </div>
                </section>
                {/* Cards  End*/}
                <div className='mt-[20px] overflow-x-auto pb-8'>
                    <table className='table-fixed w-[750px] md:w-full rounded-lg' style={{ 'boxShadow': '0px 0px 20px #D7DEE365' }}>
                        <thead >
                            <tr className='bg-[#08488C]'>
                                <th className='py-[11px] text-xs text-white font-light text-start  pl-[36px] w-[200px]'>VILLA NAME</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>REQUEST ID</th>
                                <th className='py-[11px] text-xs text-white font-light text-start w-[100px]'>CITY</th>
                                <th className='py-[11px] text-xs text-white font-light text-start pr-8'>DATE</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>VENDOR ID</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>STATUS</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>ACTION</th>
                            </tr>
                        </thead>
                        <tbody>
                            {villasList.map((item, index) => {

                                return (
                                    <Link
                                        href={`/villas/villa_details/${[item?.villa_id]}`}
                                        key={index + ''}
                                    >
                                        <tr className='border-b last:border-b-0 border-[#EFF3F9] cursor-pointer'>
                                            <td className=' pl-[36px] py-[24px] text-[#54617A]  text-sm font-roboto '>{item?.villa_name}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>{item?.request_id}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm '>{item?.city}</td>
                                            <td className='  py-[24px] pr-8 text-[#54617A] font-roboto text-sm'>{item?.request_date}</td>
                                            <td className='  py-[24px] text-black font-roboto text-sm'>{item?.vendor_id}</td>
                                            <td className={`py-[24px] ${item?.status == 'yes' ? "text-green-500" : "text-red-500"} font-medium font-roboto text-sm`}>{item?.status == 'yes' ? "Approved" : "Pending"}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm cursor-pointer'>
                                                <Link href={`/villas/villa_details/${[item?.villa_id]}`}>
                                                    <svg xmlns="http://www.w3.org/2000/svg"
                                                        fill="none"
                                                        viewBox="0 0 24 24"
                                                        stroke-width="1.5"
                                                        stroke="#08488C"
                                                        class="w-6 h-6">
                                                        <path
                                                            stroke-linecap="round"
                                                            stroke-linejoin="round"
                                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                                    </svg>
                                                </Link>

                                            </td>
                                        </tr>
                                    </Link>
                                )
                            })}
                        </tbody>
                    </table>
                    {/* Pagination */}
                    <PaginationElement
                        currentPage={pageNumber}
                        callBack={(currentPage) => { setPageNumber(currentPage) }}
                        totalPages={lastPage}
                    />
                </div>
            </Layout>
            {loading && <Loader />}
        </>
    )
}

export default index