import React, { useState } from 'react';
import Layout from '../../../components/Layout';
import Head from 'next/head';
import UserCard from '../../../components/reservations/UserCard';
import BookingModal from '../../../components/Modal/index';
import { useRouter } from 'next/router';

const index = () => {
    const [isOpen, setIsOpen] = useState(false)
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Reservation details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BookingModal isOpen={isOpen} setIsOpen={setIsOpen} className="py-16 w-full lg:w-[837px]">
                <div className='w-full sm:w-[450px] mx-auto flex flex-col justify-center items-center'>
                    <img src='/img/success.svg' alt='Success' />
                    <h1 className='font-semibold text-[32px] text-primary mt-3'>Booking Is Successful</h1>
                    <p className='text-center text-[#5C5C5C] text-base'>Booking reservation is successfully approved and notify the Villa Vendor about Order# 90890809</p>
                    <div className='text-center mt-12'>
                        <button className='w-[150px] h-[42px] text-white text-sm font-light rounded-xl bg-darkGreen'
                            onClick={() => setIsOpen(false)}
                        >That's great!</button>
                    </div>
                </div>
            </BookingModal>
            <Layout title="Request Detail">
                <section className='pr-4 pb-7'>
                    <div className='flex justify-between items-center mt-3'>
                        <div>
                            <h1 className='text-[24px] text-black font-sans font-medium'>Booking ID #213213</h1>
                            <p className='text-lightGray text-base py-1 font-sans'>24 Sept 2022</p>
                            <p className='text-lightGray text-base font-sans'>Status <span className='text-danger font-semibold'> Pending</span></p>
                        </div>
                        <button className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'>Approve Booking</button>
                    </div>
                    <div className='md:flex flex-wrap justify-center md:justify-between mt-10'>
                        <div>
                            <div className='mt-10'>
                                <h4 className='text-xl text-darkBlack font-medium'>More Information:</h4>
                                <div className='mt-5'>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Req name or descroption</p>
                                        <p className='text-black text-base'>Saleh Hayat</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>About User</p>
                                        <p className='text-black text-base'>Vendor</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Name of user</p>
                                        <p className='text-black text-base'>Saleh Hayat</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>User ID</p>
                                        <p className='text-black text-base'>231321</p>
                                    </div>

                                    <div className='flex mb-7'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Amount</p>
                                        <p className='text-base text-darkBlack font-medium w-[300px]'>$2300.00</p>
                                    </div>
                                    <div className='flex mb-7'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Transfer to</p>
                                        <p className='text-base text-darkBlack font-medium w-[300px]'>Bank Transfer</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-lg text-darkBlack font-medium w-[300px]'>Actions</p>
                                        <div className='w-[350px]'>
                                            <div className='w-[192px] h-[35px] relative'>
                                                <select
                                                    className='w-full h-full text-sm text-darkBlack appearance-none rounded-[25px] border font-roboto border-[#94BAD4] px-5'
                                                    style={{ boxShadow: '0px 2px 20px #CFD9DF66' }}
                                                >
                                                    <option selected>Pause Vendor</option>
                                                </select>
                                                <img src='/img/down.svg' alt="down" className='absolute right-4 top-1/2 -translate-y-1/2 w-[20px] h-[12px]' />
                                            </div>
                                            <p className='font-medium text-xs text-black mt-3'>Select action and it will notify the vendor and system listing automatically</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className='mt-5'>
                                <div className='flex gap-x-10 mt-8'>
                                    <button
                                        className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'
                                        onClick={() => setIsOpen(true)}
                                    >Approve Request</button>
                                    <button className='w-[176px] h-[46px] bg-[#AEC4DB] text-white font-light text-sm rounded-[14px]' onClick={() => router.back()}>Cancel</button>
                                </div>
                            </div>
                        </div>
                        <div className=''>
                            <UserCard title="About User" />
                        </div>
                    </div>
                </section>
            </Layout>
        </>
    )
}

export default index