import React, { useState } from 'react';
import Layout from '../../../components/Layout';
import Head from 'next/head';
import UserCard from '../../../components/reservations/UserCard';
import Link from 'next/link';

const index = () => {
    return (
        <>
            <Head>
                <title>Villa details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout title="Cancellation Request Detail">
                <section className='pr-4 pb-7'>
                    <div className='flex justify-between items-center mt-3'>
                        <div>
                            <h1 className='text-[24px] text-black font-sans font-medium'>Request ID #213213</h1>
                            <p className='text-lightGray text-base py-1 font-sans'>Joining Date: 24 Sept 2022</p>
                            <p className='text-lightGray text-base font-sans'>Status <span className='text-danger font-semibold'>  Pending</span></p>
                        </div>
                        <button className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'>Approve Booking</button>
                    </div>
                    <div className='md:flex flex-wrap justify-center md:justify-between mt-10'>
                        <div className=''>
                            <h4 className='text-xl text-darkBlack font-medium'>Villa Information</h4>
                            <div className='mt-5'>
                                <div className='flex mb-3'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>Request by</p>
                                    <p className='text-black text-base'>Abid alam</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>About User</p>
                                    <p className='text-primary font-semibold text-base'>User</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>Name of user</p>
                                    <p className='text-black text-base'>Name of user</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>User ID</p>
                                    <p className='text-black text-base'>231321</p>
                                </div>
                                <div className='flex mb-5'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>Amount</p>
                                    <p className='text-black font-semibold text-base'>$2300.00</p>
                                </div>
                                <div className='flex mb-5'>
                                    <p className='text-[#6C7A87] font-light text-base sm:w-[300px]'>Transfer to</p>
                                    <div>
                                        <p className='text-black font-semibold text-base'>Bank Transfer</p>
                                        <p className='text-[#6C7A87] font-light text-base font-sans'>Account Info here</p>
                                    </div>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-lg text-darkBlack font-medium w-[300px]'>Actions</p>
                                    <div>
                                        <div className='w-[192px] h-[35px] relative'>
                                            <select
                                                className='w-full h-full text-sm text-darkBlack appearance-none rounded-[25px] border border-[#94BAD4] px-5'
                                                style={{ boxShadow: '0px 2px 20px #CFD9DF66' }}
                                            >
                                                <option selected>Approve Request</option>
                                            </select>
                                            <img src='/img/down.svg' alt="down" className='absolute right-4 top-1/2 -translate-y-1/2 w-[20px] h-[12px]' />
                                        </div>
                                        <p className='text-xs text-black font-medium mt-3 w-[350px]'>Select action and it will notify the vendor and system listing automatically</p>
                                    </div>
                                </div>

                            </div>
                        </div>
                        {/* Booking details card */}
                        <div className='w-[340px] rounded-3xl px-6 py-8' style={{ boxShadow: "0px 0px 20px #D7DEE365" }}>
                            <h1 className='text-xl font-medium text-primary'>About Booking</h1>
                            <div className={`w-full flex flex-col items-center mt-6`}>
                                <img src="/img/villa1.jpg" alt='Profile' className='w-[173px] h-[120px] rounded-[13px] object-cover' />
                                <h1 className='text-lg font-medium text-darkBlack mt-3'>Villa name here</h1>
                                <p className='text-xs text-darkBlack font-sans font-medium'>Vendor ID: 322131</p>
                            </div>
                            <div className='mt-8 pl-6'>
                                <div className='flex items-center my-4'>
                                    <p className='w-[80px] font-light text-lightGray text-xs'>City: </p>
                                    <p className='text-darkBlack text-xs'>Riyadh</p>
                                </div>
                                <div className='flex items-center my-4'>
                                    <p className='w-[80px] font-light text-lightGray text-xs'>From</p>
                                    <p className=' text-darkBlack text-xs'>25th September 2022</p>
                                </div>
                                <div className='flex items-center my-4'>
                                    <p className='w-[80px] font-light text-lightGray text-xs'>To</p>
                                    <p className=' text-darkBlack text-xs'>25th September 2022</p>
                                </div>

                            </div>
                        </div>
                        {/* End */}

                    </div>
                    <div className='flex gap-x-10 mt-20'>
                        <Link href="/villas/details">
                            <button
                                className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'
                            // onClick={() => setIsOpen(true)}
                            >Approve Request</button>
                        </Link>
                        <button className='w-[176px] h-[46px] bg-[#AEC4DB] text-white font-light text-sm rounded-[14px]'>Cancel</button>
                    </div>
                </section>
            </Layout>
        </>
    )
}

export default index