import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
// import styles from '../styles/Home.module.css'
import OtpInput from 'react-otp-input';
import { useRouter } from 'next/router'
import API from '../../utilis/API';
import Loader from '../../components/Loader';
import getHeader from '../../utilis/getHeader';
import { toast } from 'react-toastify';


export default function Home() {
    const header = getHeader();
    const router = useRouter();
    const [otp, setOtp] = useState('');

    const [loading, setLoading] = useState(false);

    // -------- Forget password handler ----------
    const verifyEmail = async () => {
        const payload = {
            email: router?.query?.email,
            otp: otp
        }
        try {
            setLoading(true)
            const { data } = await API.post('/forget/password/verifyotp', payload, header)
            if (data?.success == true) {
                toast('Email Successfully verified')
                setTimeout(() => {
                    router.push({
                        pathname: '/auth/new_password',
                        email: { email: payload?.email }
                    }, '/auth/new_password')
                }, 2000)
            } else if (data?.error) {
                toast.error(data?.error)
            }
            setLoading(false)

        } catch (error) {
            setLoading(false)
            console.log(error)
        }
    }

    return (
        <>
            {loading && <Loader />}
            <Head>
                <title>Esterahy - Email Confirmation</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full md:h-[100vh] flex flex-wrap'>
                <div className='w-full lg:w-1/2 bg-primaryLight flex justify-center items-center'>
                    <div className='w-full px-6 md:px-12 lg:px-24 py-12 md:py-16 lg:py-0'>
                        <img src='/img/logo.png' alt='Logo' className='w-[160px] md:w-[228px] md:h-[100px] mx-auto' />
                        <div className='mt-6'>
                            <h1 className='text-primary text-[22px] md:text-[28px] font-semibold'>Email Confirmation</h1>
                            <p className='mt-1 text-darkGray text-base'>6 Digits confirmation code has been sent to your registered email Fais*********gmail.com</p>
                        </div>
                        <form className='mt-12' >
                            <div className='w-full pb-16 border-b border-blue-200'>
                                <div className='w-full opt__wrapper'>
                                    <OtpInput
                                        value={otp}
                                        onChange={(otp) => setOtp(otp)}
                                        numInputs={4}
                                    />
                                </div>
                                <Link href="/auth/forget_password">
                                    <p className='text-xs font-medium w-full text-right mt-4 cursor-pointer'>Send again</p>
                                </Link>
                            </div>
                            <div className='flex justify-between mt-7 items-center'>
                                <button className="text-xs font-medium" onClick={() => router.back()}>Back</button>
                                {/* <Link href="/auth/new_password"> */}
                                <button
                                    className='w-[150px] h-[42px] rounded-xl bg-primary text-xs text-white uppercase'
                                    onClick={(e) => {
                                        e.preventDefault();
                                        verifyEmail();
                                    }}
                                >Confirm Now</button>
                                {/* </Link> */}
                            </div>
                        </form>
                    </div>
                </div>
                <div className='w-full lg:w-1/2'>
                    <img src='/img/forgot.png' alt='' className='w-full lg:h-[100vh]' />
                </div>
            </main>
        </>
    )
}
