import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react';
import { toast } from 'react-toastify';
import Loader from '../../components/Loader';
import API from '../../utilis/API';
import getHeader from '../../utilis/getHeader';

export default function Home() {
    const header = getHeader();
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [loading, setLoading] = useState(false);

    // -------- Forget password handler ----------
    const recoverAccount = async () => {
        const payload = {
            'email': email
        }
        try {
            setLoading(true)
            const { data } = await API.post('forget/password/sendotp', payload, header)
            if (data?.success == true) {
                toast('Verification code has been send to your email')
                setTimeout(() => {
                    router.push({
                        pathname: '/auth/email_confirmation',
                        query: { email: email }
                    }, '/auth/email_confirmation')
                }, 2000)

            } else if (data?.error) {
                toast.error(data?.error)
            }
            setLoading(false)

        } catch (error) {
            setLoading(false)
            console.log(error)
        }
    }

    return (
        <>
            {loading && <Loader />}
            <Head>
                <title>Esterahy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full md:h-[100vh] flex flex-wrap'>
                <div className='w-full lg:w-1/2 bg-primaryLight flex justify-center items-center'>
                    <div className='w-full px-6 md:px-12 lg:px-24 py-12 md:py-16 lg:py-0'>
                        <img src='/logo.png' alt='Logo' className='w-[160px] md:w-[228px] md:h-[100px] mx-auto' />
                        <div className='mt-6'>
                            <h1 className='text-primary text-[22px] md:text-[28px] font-semibold'>Forget your password?</h1>
                            <p className='mt-1 text-darkGray text-base'>Recover your password by entering your registered email and usernamed</p>
                        </div>
                        <form className='mt-12'>
                            <div className='w-full pb-12 border-b border-blue-200'>
                                {/* <div className='w-full flex gap-x-12 flex-wrap items-center mb-8'>
                                    <label className='font-medium w-[100px]'>Username</label>
                                    <input type="text" className='flex-1 h-[42px] rounded-lg border border-primary px-4 mt-2 sm:mt-0' />
                                </div> */}
                                <div className='w-full flex gap-x-12 items-center flex-wrap'>
                                    <label className='font-medium w-[100px]'>Email</label>
                                    <input
                                        type="email"
                                        className='flex-1 h-[42px] rounded-lg border border-primary px-4 mt-2 sm:mt-0'
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                    />
                                </div>
                            </div>
                            <div className='flex justify-between mt-7 items-center'>
                                <Link href="/">
                                    <button className="text-xs font-medium">Back</button>
                                </Link>
                                {/* <Link href="/auth/email_confirmation"> */}
                                <button
                                    className='w-[150px] h-[42px] rounded-xl bg-primary text-xs text-white uppercase'
                                    onClick={(e) => {
                                        e.preventDefault();
                                        recoverAccount();
                                    }}
                                >Recover now</button>
                                {/* </Link> */}
                            </div>
                        </form>
                    </div>
                </div>
                <div className='w-full lg:w-1/2'>
                    <img src='/img/forgot.png' alt='' className='w-full lg:h-[100vh]' />
                </div>
            </main>
        </>
    )
}
