import React, { useState, useEffect } from 'react';
import Layout from '../../components/Layout';
import Head from 'next/head';
import UserCard from '../../components/reservations/UserCard';
import BookingModal from '../../components/Modal/index';
import Loader from '../../components/Loader';
import getHeader from '../../utilis/getHeader';
import API from '../../utilis/API';
import { useRouter } from 'next/router';
import Link from 'next/link';

const index = (props) => {
    const router = useRouter();
    const [isOpen, setIsOpen] = useState(false)
    const [loading, setloading] = useState(false);

    const [detailsData, setdetailsData] = useState();

    const loadDetailsData = async () => {
        setloading(true)
        try {
            const header = getHeader()
            const id = props?.id
            const { data } = await API.get(`Dashboard/reservation/detail/${id}`, header)
            console.log("reservation detials: ", data?.body)
            setdetailsData(data?.body)
            setloading(false)
        } catch (error) {
            console.log(error)
            setloading(false)
        }
    }

    useEffect(() => {
        loadDetailsData()
    }, [props?.id]);

    const bookingStatus = detailsData?.booking_detail?.booking_status

    return (
        <>
            <Head>
                <title>Reservation details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BookingModal isOpen={isOpen} setIsOpen={setIsOpen} className="py-16 w-full lg:w-[837px]">
                <div className='w-full sm:w-[450px] mx-auto flex flex-col justify-center items-center'>
                    <img src='/img/success.svg' alt='Success' />
                    <h1 className='font-semibold text-[32px] text-primary mt-3'>Booking Is Successful</h1>
                    <p className='text-center text-[#5C5C5C] text-base'>Booking reservation is successfully approved and notify the Villa Vendor about Order# 90890809</p>
                    <div className='text-center mt-12'>
                        <button className='w-[150px] h-[42px] text-white text-sm font-light rounded-xl bg-darkGreen'
                            onClick={() => setIsOpen(false)}
                        >That's great!</button>
                    </div>
                </div>
            </BookingModal>
            <Layout title="Reservation Details">
                <section className='pr-4 pb-7'>
                    <div className='flex justify-between items-center mt-3'>
                        <div>
                            <h1 className='text-[24px] text-black font-sans font-medium'>{`Booking ID #${detailsData?.booking_detail?.booking_id}`}</h1>
                            <p className='text-lightGray text-base py-1 font-sans'>{detailsData?.booking_detail?.check_in_date}</p>
                            <p className='text-lightGray text-base font-sans'>Status: <span className={`font-semibold ${bookingStatus == "Confirmed" ? "text-green-500" : "text-danger"}`}>{detailsData?.booking_detail?.booking_status}</span></p>
                        </div>
                        {/* <button className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'>Approve Booking</button> */}
                    </div>
                    <div className='md:flex flex-wrap justify-center md:justify-between mt-10'>
                        <div>
                            <div className='flex gap-x-7 items-center'>
                                <img src='/img/village.png' alt='' className='w-[120px] h-[120px]' />
                                <div>
                                    <h5 className='text-lg font-medium text-darkBlack'>{detailsData?.villa_detail?.name}</h5>
                                    <p className='text-xs text-black'>Vendor ID: {detailsData?.vendor_detail?.vendor_id}</p>
                                    <p className='text-lightGray text-sm py-1 font-sans'>City: {detailsData?.villa_detail?.city}</p>
                                    <div className='flex items-center'>
                                        <p className='text-lightGray text-xs py-1 font-sans w-12'>From</p>
                                        <p className='text-xs text-black'>{detailsData?.booking_detail?.check_in_date}</p>
                                    </div>
                                    <div className='flex items-center'>
                                        <p className='text-lightGray text-xs py-1 font-sans w-12'>To</p>
                                        <p className='text-xs text-black'>{detailsData?.booking_detail?.check_out_date}</p>
                                    </div>
                                </div>
                            </div>
                            <div className='mt-10'>
                                <h4 className='text-xl text-darkBlack font-medium'>Booking Details:</h4>
                                <div className='mt-5'>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Customer name</p>
                                        <p className='text-black text-base'>{detailsData?.customer_detail?.name}</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Email</p>
                                        <p className='text-black text-base'>{detailsData?.customer_detail?.email}</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Contact No</p>
                                        <p className='text-black text-base'>{detailsData?.customer_detail?.phone}</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Booking dates</p>
                                        <p className='text-black text-base'>{detailsData?.booking_detail?.check_in_date}</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Number of bed</p>
                                        <p className='text-black text-base'>{detailsData?.villa_detail?.no_of_beds}</p>
                                    </div>
                                </div>
                            </div>
                            <div className='my-7 w-full'>
                                <h4 className='text-xl text-darkBlack font-medium'>Payment Details</h4>
                                <div className='mt-5'>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Payment Status</p>
                                        <p className='text-success text-base font-medium'>{detailsData?.payment_detail?.payment_status}</p>
                                    </div>
                                    <div className='flex mb-3'>
                                        <p className='text-darkGray font-light text-base sm:w-[300px]'>Payment Method</p>
                                        <p className='text-black text-base'>{detailsData?.payment_detail?.payment_through}</p>
                                    </div>
                                    <div className='flex mb-7'>
                                        <p className='text-lg text-darkBlack font-medium w-[300px]'>Amount</p>
                                        <p className='text-lg text-darkBlack font-medium w-[300px]'>{detailsData?.payment_detail?.amount}</p>
                                    </div>


                                </div>
                            </div>
                        </div>
                        <div className=''>
                            <UserCard title="About Vendor" img="/img/profile.jpg" data={detailsData?.vendor_detail} />
                        </div>
                    </div>
                </section>
            </Layout>
            {loading && <Loader />}
        </>
    )
}

export async function getServerSideProps(context) {

    return {
        props: {
            id: context?.query?.id
        }
    }
}

export default index





