import React, { useState, useEffect } from 'react';
import Layout from '../../components/Layout';
import Head from 'next/head';
import UserCard from '../../components/reservations/UserCard';
import BookingModal from '../../components/Modal/index';
import Search from '../../components/SVGs/Search';
import Link from 'next/link';
import getHeader from '../../utilis/getHeader';
import API from '../../utilis/API';
import Loader from '../../components/Loader';
import PaginationElement from '../../components/PaginationElement';

const index = () => {


    const [cardsData, setCardsData] = useState([

    ]);
    const [loading, setloading] = useState(false);
    const [cancelledReservationsList, setCancelledReservationsList] = useState([]);

    // For pagination
    const [pageNumber, setPageNumber] = useState(1)
    const [lastPage, setLastPage] = useState();

    const loadVillasList = async () => {
        setloading(true)
        try {
            const header = getHeader()
            const { data } = await API.get(`Dashboard/reservations/cancelled?page=${pageNumber}`, header)
            console.log("cancel",data);
            
            setCardsData([
                {
                    title: 'Cancelled',
                    value: data?.body?.cancelled_reservations,
                    color: '#F52D56'
                }
            ])
            setCancelledReservationsList(data?.body?.reservation_list?.data)
            setLastPage(data?.body?.reservation_list?.last_page);

            setloading(false)
        } catch (error) {
            console.log(error)
            setloading(false)
        }
    }


    useEffect(() => {
        loadVillasList()
    }, [pageNumber]);

    return (
        <>
            <Head>
                <title>Esterahy - Cancelled Reservations</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout title="All Cancelled Reservations" slug="Explore all villa reservations here">
                {/* Cards  Start*/}
                <section className='w-full border-b pb-8'>
                    <div className='flex flex-row flex-wrap space-x-[24px] mt-[29px]'>
                        {
                            cardsData?.map((item, index) => {
                                return (
                                    <div
                                        key={index + ''}
                                        className='w-[209px] h-[135px] bg-white rounded-[8px] flex flex-col pt-[22px] px-[25px]'
                                        style={{
                                            'boxShadow': '0px 0px 20px #D7DEE365'
                                        }}
                                    >
                                        <h1 className={`font-roboto text-darkBlack text-xl font-medium`}>{item?.title}</h1>
                                        <h2 className={`font-roboto font-bold text-[${item?.color}] text-2xl mt-[13px]`}>{item?.value}</h2>
                                    </div>
                                )
                            })
                        }
                    </div>
                </section>
                <div className='mt-[20px] pb-8'>
                    <table className='table-fixed w-full rounded-lg' style={{ 'boxShadow': '0px 0px 20px #D7DEE365' }}>
                        <thead >
                            <tr className='bg-[#08488C]'>
                                <th className='py-[11px] text-xs text-white font-light text-start  pl-[36px] w-[200px]'>VILLA NAME</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>CUSTOMER ID</th>
                                <th className='py-[11px] text-xs text-white font-light text-start w-[100px]'>CITY</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>DATE</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>BOOKING ID</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>AMOUNT</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>STATUS</th>
                                <th className='py-[11px] text-xs text-white font-light text-start'>ACTION</th>
                            </tr>
                        </thead>
                        <tbody>
                            {cancelledReservationsList?.map((item, index) => {

                                return (
                                    <Link
                                        href={`/reservations/${[item?.id]}`}
                                        key={index + ''}
                                    >
                                        <tr className='border-b last:border-b-0 border-[#EFF3F9] cursor-pointer'>
                                            <td className=' pl-[36px] py-[24px] text-[#54617A]  text-sm font-roboto '>{item?.villa_name}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>{item?.customer_id}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm '>{item?.city}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>{item?.date}</td>
                                            <td className='  py-[24px] text-black font-roboto text-sm'>{"Not available"}</td>
                                            <td className='  py-[24px] text-black font-roboto text-sm'>{item?.amount}</td>
                                            <td className='  py-[24px] text-[#F52D56] font-medium font-roboto text-sm'>{item?.status}</td>
                                            <td className='  py-[24px] text-[#54617A] font-roboto text-sm cursor-pointer'>
                                                <Link href={`/villas/villa_details/${[item?.villa_id]}`}>
                                                    <svg xmlns="http://www.w3.org/2000/svg"
                                                        fill="none"
                                                        viewBox="0 0 24 24"
                                                        stroke-width="1.5"
                                                        stroke="#08488C"
                                                        class="w-6 h-6">
                                                        <path
                                                            stroke-linecap="round"
                                                            stroke-linejoin="round"
                                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                                    </svg>
                                                </Link>

                                            </td>
                                        </tr>
                                    </Link>
                                )
                            })}
                        </tbody>
                    </table>
                    {/* Pagination */}
                    <PaginationElement
                        currentPage={pageNumber}
                        callBack={(currentPage) => { setPageNumber(currentPage) }}
                        totalPages={lastPage}
                    />
                </div>
            </Layout>
            {loading && <Loader />}
        </>
    )
}

export default index