import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { LOGIN_DATA_KEY } from '../utilis/constants'
import API from '../utilis/API'
import { setCookie } from 'cookies-next';
import { useRouter } from 'next/router'
import { toast } from 'react-toastify';
import Loader from '../components/Loader'

export default function Home() {
  const router = useRouter();

  const [payload, setPayload] = useState({
    email: 'thekillerk413@gmail.com',
    password: 'password'
  });
  const [loading, setLoading] = useState(false);

  // -------- Login handler ----------
  const loginUser = async () => {
    let header = {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    }
    try {
      const formData = new FormData()
      formData.append('email', payload?.email)
      formData.append('password', payload?.password)

      setLoading(true)
      const { data } = await API.post('Dashboard/login', formData, header)
      if (data?.success) {
        setCookie(LOGIN_DATA_KEY,
          data?.body, {
          secure: false
        })
        router.push('/dashboard')
        toast('Login Successful!')
      } else if (data?.error) {
        toast.error(data?.error)
      }
      setLoading(false)

    } catch (error) {
      setLoading(false)
      console.log(error)
    }
  }


  return (
    <>
      {loading && <Loader />}
      <Head>
        <title>Esterahy - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full md:h-[100vh] flex flex-wrap'>
        <div className='w-full lg:w-1/2 bg-primaryLight flex justify-center items-center'>
          <div className='w-full px-6 md:px-12 lg:px-24 py-12 md:py-16 lg:py-0'>
            <img src='/img/logo.png' alt='Logo' className='w-[160px] md:w-[228px] md:h-[100px] mx-auto' />
            <div className='mt-6'>
              <h1 className='text-primary text-[22px] md:text-[28px] font-semibold'>Login</h1>
              <p className='mt-1 text-darkGray text-base'>Please enter your authorized username or password</p>
            </div>
            <form className='mt-12'>
              <div className='w-full pb-10 border-b border-blue-200'>
                <div className='w-full flex gap-x-12 flex-wrap items-center mb-8'>
                  <label className='font-medium w-[100px]'>Username</label>
                  <input
                    value={payload?.email}
                    onChange={e => setPayload({ ...payload, email: e.target.value })}
                    type="text"
                    className='flex-1 h-[42px] rounded-lg border border-primary px-4 mt-2 sm:mt-0 '
                  />
                </div>
                <div className='w-full flex gap-x-12 items-center flex-wrap'>
                  <label className='font-medium w-[100px]'>Password</label>
                  <input
                    type="password"
                    className='flex-1 h-[42px] rounded-lg border border-primary px-4 mt-2 sm:mt-0 '
                    value={payload.password}
                    onChange={e => setPayload({ ...payload, password: e.target.value })}
                  />
                </div>
                <Link href="/auth/forget_password">
                  <p className='text-xs font-medium w-full text-right mt-4 cursor-pointer'>Forget password?</p>
                </Link>
              </div>
              <div className='text-right'>
                <button
                  onClick={e => {
                    e.preventDefault()
                    loginUser()
                  }}
                  className='w-[150px] h-[42px] rounded-xl bg-primary text-xs text-white uppercase mt-7'>Login</button>
              </div>
            </form>
          </div>
        </div>
        <div className='w-full lg:w-1/2'>
          <img src='/img/login.png' alt='' className='w-full lg:h-[100vh]' />
        </div>
      </main>
      {/* <Loader /> */}
    </>
  )
}
