import React from 'react';
import Layout from '../../components/Layout';
import Head from 'next/head';
import { LineChart, YAxis, XAxis, CartesianGrid, Tooltip, Legend, Line, ResponsiveContainer } from 'recharts';
import Link from 'next/link';

const Index = () => {

    const cardsdata = [
        {
            title: 'New Request',
            value: '45,320',
            percentageValue: '5.25%'
        },
        {
            title: 'Earnings',
            value: '45,320',
            percentageValue: '7.85%'
        },
        {
            title: 'Pendings',
            value: '33',
            percentageValue: '',
        },

    ]

    return (
        <>
            <Head>
                <title>Esterahy - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout title="Payment Requests" slug="Check payment credit and debit request">
                <div className='pt-[30px]'>
                    <div className='grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-x-[10px] gap-y-[13px] mt-[28px]  border-b-2 pb-10'>
                        {
                            cardsdata.map((item, index) => {
                                return (
                                    <div
                                        key={index + ''}
                                        className='flex flex-col pt-[10px] md:pt-[22px] pb-[14px] md:pb-[28px] bg-white rounded-lg pl-[15px] md:pl-[25px]'
                                        style={{
                                            'boxShadow': '0px 0px 20px #D7DEE365'
                                        }}
                                    >
                                        <h1 className='text-[#2E3039] text-xl'>{item?.title}</h1>
                                        <h1 className={`${index == 2 ? "text-[#F52D56]" : "text-[#242E42]"}
                                                 text-[24px] font-semibold mt-2 md:mt-[13px]` }>{item?.value}</h1>
                                        {index !== 2 && <>
                                            <div className='flex flex-row items-center  mt-2 md:mt-[18px] space-x-1'>
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="#03DE73" viewBox="0 0 24 24" stroke-width="1.5" stroke="#03DE73" class="w-3 h-3">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 19.5v-15m0 0l-6.75 6.75M12 4.5l6.75 6.75" />
                                                </svg>

                                                <h1 className={`${index < 2 ? "text-[#03DE73]" : "text-[#F52D56]"} text-sm `}>{item.percentageValue}</h1>
                                            </div>
                                            <h1 className='text-[#54617A] text-xs mt-[7px] opacity-50'>Since last month</h1>
                                        </>
                                        }
                                    </div>
                                )
                            })
                        }
                        <div
                            key={"6"}
                            className='flex flex-row flex-wrap sm:flex-nowrap items-start pt-[10px] md:pt-[22px] pb-[14px] md:pb-[28px] bg-white 
                                        rounded-lg px-[15px] md:px-[25px]  col-span-1 md:col-span-2 space-x-4'
                            style={{
                                'boxShadow': '0px 0px 20px #D7DEE365'
                            }}
                        >   <div className=''>
                                <h1 className='text-[#2E3039] text-xl font-roboto font-light'>{'This Month'}</h1>
                                <h1 className={`text-[#242E42] text-[24px] font-semibold mt-2 md:mt-[13px]`}>+35.52</h1>
                            </div>
                            <div className='flex-1 relative h-20'>
                                <ResponsiveContainer>
                                    <LineChart
                                        data={new Array(16).fill(null).map((item, i) => {
                                            return {

                                                "name": i + '',
                                                "pv": 1000 + Math.random() * 10000 * i + 300 * i,
                                                "amt": 2400
                                            }

                                        })}
                                        width='100%'
                                    >

                                        <Line
                                            type="monotone"
                                            dataKey="pv"
                                            stroke="#61DD9F"
                                            strokeWidth={2.5}
                                            dot={false}
                                        />

                                    </LineChart>
                                </ResponsiveContainer>

                            </div>
                        </div>
                    </div>
                </div>
                <div className='pt-[30px]'>
                    {/* Table start */}
                    <div
                        className='bg-white mt-[28px] rounded-[8px] relative mb-10'
                        style={{
                            'boxShadow': '0px 0px 20px #D7DEE365'
                        }}
                    >
                        <table className='table-fixed w-full'>
                            <thead >
                                <tr className='bg-[#08488C] '>
                                    <th className='py-[11px] text-xs text-white font-light text-start  pl-[36px] w-[200px]'>REQUEST NAME OR DESC</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start'>ID</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start'>REQUEST TYPE</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start w-[100px]'>DATE</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start pl-[20px]'>USER ID</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start'>AMOUNT</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start'>STATUS</th>
                                    <th className='py-[11px] text-xs text-white font-light text-start'>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                {new Array(10).fill(null).map((item, index) => {
                                    return (
                                        <Link href="/payments/request_details">
                                            <tr className='border-b last:border-b-0 border-[#EFF3F9] cursor-pointer'>
                                                <td className=' pl-[36px] py-[24px] text-[#54617A]  text-sm font-roboto '>Add into wallet   </td>
                                                <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>#1224322</td>
                                                <td className='  py-[24px] text-[#54617A] font-roboto text-sm '>Credit</td>
                                                <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>07 to -09 April 2018</td>
                                                <td className='  py-[24px] text-[#54617A] font-roboto text-sm pl-[20px]'>#1224322</td>
                                                <td className='  py-[24px] text-[#54617A] font-roboto text-sm'>$129.99</td>
                                                <td className='  py-[24px] text-[#F52D56] font-medium font-roboto text-sm'>PENDING</td>
                                                <td
                                                    className='  py-[24px] text-[#54617A] font-roboto text-sm cursor-pointer'
                                                >
                                                    <Link href="/reservations/reservation_details">
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                            fill="none"
                                                            viewBox="0 0 24 24"
                                                            stroke-width="1.5"
                                                            stroke="#08488C"
                                                            class="w-6 h-6">
                                                            <path
                                                                stroke-linecap="round"
                                                                stroke-linejoin="round"
                                                                d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                                        </svg>
                                                    </Link>

                                                </td>
                                            </tr>
                                        </Link>
                                    )
                                })}
                            </tbody>
                        </table>

                    </div>
                    {/* Table end */}
                </div>
            </Layout>
        </>
    );
}

export default Index;
